### ISSUE TITLE
find: cannot delete ‘/usr/local/tmp/sessions/

### ISSUE THREAD

**Issue by daleosm** [criegerde/install-nextcloud#11]
My syslog is streaming out a constant river of the following message:

`Aug 3 11:09:02 nextcloud sessionclean[20013]: find: cannot delete ‘/usr/local/tmp/sessions/sess_1f3k8alpa5ueamq8umq18eketi’: Read-only file system`

**Caused by:**
`sed -i '$atmpfs /usr/local/tmp/apc tmpfs defaults,uid=33,size=300M ... -R www-data:root /usr/local/tmp/sessions`

I can see this is set for a reason but how can I suppress the output to my syslog?

**Comment by criegerde** [comment]
I guess it is caused by an older version of my scripts - tmpfs was used added to /etc/fstab?!

simply remove it from as well 
`/etc/php/7.3/cli/php.ini`
as
`/etc/php/7.3/fpm/php.ini`
and 
finally umount it and remove it from 
`/etc/fstab.`

Restart php and the errors should no longer appear.

**Comment by daleosm** [comment]
Thanks. I used /u/ReinerNippes Ansible Playbook and thought it would pull your latest recommendations but on deeper inspection it's a conversion of an older version.
