### ISSUE TITLE
optimize-debian redis.sock

### ISSUE THREAD

**Issue by john-arvid** [criegerde/install-nextcloud#12]
When I run the script I get "Could not connect to Redis at /var/run/redis/redis.sock: No such file or directory"
When I check the directory I only find redis-server.sock

Running Debian 10

**Comment by criegerde** [comment]
Something went wrong. The directory structure should look like the screenshot:
![grafik](https://user-images.githubusercontent.com/47498887/66269063-408e5280-e844-11e9-8863-f26b350b80fa.png)
