### ISSUE TITLE
pretty urls is not working

### ISSUE THREAD

**Issue by inos-github** [criegerde/install-nextcloud#13]
I  have installed NC on an Ubuntu server by using your script and out of the box, pretty url is not working for me.
Do you have any idea?
I have an installation on an arm device running debian stretch, and nginx 1.10 with php 7.3.8, NC 16 and there it's working flawlessly...

**Comment by criegerde** [comment]
It is enabled by default as well on Ubuntu as on Debian - i did  a fresh install and everything is as expected:
![grafik](https://user-images.githubusercontent.com/47498887/66269090-b2ff3280-e844-11e9-8003-2549647db9ec.png)

![grafik](https://user-images.githubusercontent.com/47498887/66269112-e2ae3a80-e844-11e9-8826-47ca1be8ea7b.png)
