### ISSUE TITLE
Currently not working on Ubuntu 18.04 due to libidn2-0 issues

### ISSUE THREAD

**Issue by crsleeth** [criegerde/install-nextcloud#14]
Script fails at first curl. Solution by so_ to fix libidn2-0 here: https://superuser.com/questions/1466648/kali-linux-failed-after-upgrade

```
wget http://mirrors.kernel.org/ubuntu/pool/main/libi/libidn2/libidn2-0_2.0.4-1.1build2_amd64.deb
sudo dpkg -i libidn2-0_2.0.4-1.1build2_amd64.deb
sudo apt-mark hold libidn2-0

**Comment by realkot** [comment]
Haven't faced this issue, but in script a little bit strange, that we are installing curl later than using it:
![image](https://user-images.githubusercontent.com/24507273/66261003-e99a6600-e7ce-11e9-9417-263a7271428b.png)

**Comment by realkot** [comment]
Made some tests, and can't reproduce this issue:
![image](https://user-images.githubusercontent.com/24507273/66261443-01291d00-e7d6-11e9-8eeb-f6c38fa61d29.png)
@crsleeth can u confirm, that issue still persist?

**Comment by crsleeth** [comment]
I don't think its an issue any longer. Likely just a temporary issue with Ubuntu's repo.
