### ISSUE TITLE
Failes on Debian 10

### ISSUE THREAD

**Issue by vonglahn** [criegerde/install-nextcloud#16]
The script failes on a freshly installed debian 10. I tried to install a testserver using hyper-V on Windows 10.

The script reports that nextcloud is not installed and the nginx failes to start.

**Comment by Akito13** [comment]
@vonglahn Could you post the output on your console?

**Comment by vonglahn** [comment]
Hy there,

i solved it. It's because "sudo" was not installed on that maschine (I use "su -"). The script sucessfully finished after installing "sudo".

**Comment by criegerde** [comment]
i will make an enhancemen regarding sudo.
