### ISSUE TITLE
Ubuntu 18.04 Issues with nginx

### ISSUE THREAD

**Issue by realkot** [criegerde/install-nextcloud#17]
![image](https://user-images.githubusercontent.com/24507273/66260293-75a79000-e7c5-11e9-9ef6-483db82f8d92.png)

`root@VPS:~# systemctl status nginx.service
● nginx.service - A high performance web server and a reverse proxy server
   Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2019-10-05 23:06:30 MSK; 1min 23s ago
     Docs: man:nginx(8)
 Main PID: 20521 (code=exited, status=0/SUCCESS)

Oct 05 23:06:30 VPS systemd[1]: Starting A high performance web server and a reverse proxy server...
Oct 05 23:06:30 VPS nginx[23284]: nginx: [emerg] unknown directive "mp4" in /etc/nginx/conf.d/nextcloud.conf:48
Oct 05 23:06:30 VPS nginx[23284]: nginx: configuration file /etc/nginx/nginx.conf test failed
Oct 05 23:06:30 VPS systemd[1]: nginx.service: Control process exited, code=exited status=1
Oct 05 23:06:30 VPS systemd[1]: nginx.service: Failed with result 'exit-code'.
Oct 05 23:06:30 VPS systemd[1]: Failed to start A high performance web server and a reverse proxy server.
`

Failed starting can be fixed by executing:
apt-get install nginx-extras

**Comment by Akito13** [comment]
@realkot 
Thank you for providing this workaround. I just peeked into the Ubuntu script and I saw a couple of issues in need of some editing. I will look into how overhauling the script.

**Comment by realkot** [comment]
@Akito13 As u can see on screenshot, MariaDB wasn't installed too.. :(

root@VPS:/usr/local/src/install-nextcloud# mysql_secure_installation

Command 'mysql_secure_installation' not found, but can be installed with:

apt install mysql-server-5.7
apt install mariadb-server-10.1
apt install percona-xtradb-cluster-server-5.7

**Comment by realkot** [comment]
Fixed under https://github.com/criegerde/install-nextcloud/pull/19
