### ISSUE TITLE
internal server error debian 10.1

### ISSUE THREAD

**Issue by akurzawa** [criegerde/install-nextcloud#21]
clean debian 10.1 install
script install
the error:

`Internal Server Error
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.`

**Comment by Akito13** [comment]
> please include the technical details below in your report. More details can be found in the server log.

Could you follow up on that?

**Comment by akurzawa** [comment]
What log(s) do You need?
- I can confirm that the script work flawlessy on clean debian 9.9 install. I suspect it can have something to do with apparmor which is enabled by default in debian 10.1

**Comment by criegerde** [comment]
What is written to the logfiles when the error occurs?
Did it ever work after installation or did it fail while you made the installation?
