### ISSUE TITLE
Error on install-nextcloud-mariadb-debian.sh

### ISSUE THREAD

**Issue by Cripix** [criegerde/install-nextcloud#5]
Hello,

I try to install nextcloud with your script but I always have the same mistake :
![Capture](https://user-images.githubusercontent.com/30194894/57585173-b20be400-74e4-11e9-9a1d-e52e9a02f16d.PNG)

I have the same error on Ubuntu too!

**Comment by criegerde** [comment]
Please check manually as su:
`apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8`
I guess, it was [temporarily not available](https://downloads.mariadb.org/mariadb/repositories/#mirror=hs-esslingen) only.
